# MIT License
#
# Copyright (c) 2023 Almaz Ilaletdinov <a.Ilaletdinov@yandex.ru>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: 'anki-action'
description: 'Build anki cards from .md files'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'composite'
  steps:
    - run: ls -la
      shell: bash
    - run: ./entry.sh ${{ inputs.path }}
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: anki-cards
        path: /home/runner/work/anki-action/anki-action/anki-cards/cards.apkg
inputs:
  path:
    description: 'The directory with .md files'
    required: false
    default: 'anki-cards'
